name: Post On Social Media Automatically

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *" # 8 AM ET
    - cron: "0 15 * * *" # 11 AM ET
    - cron: "0 18 * * *" # 2 PM ET
    - cron: "0 21 * * *" # 5 PM ET
    - cron: "0 0 * * *" # 8 PM ET

  workflow_dispatch:

jobs:
  post-socials:
    runs-on: ubuntu-latest

    env:
      GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run Socials Agent
        run: node index.js
