name: Post Tweets Automatically

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *" # 8 AM ET
    - cron: "0 16 * * *" # 12 PM ET
    - cron: "0 22 * * *" # 6 PM ET
  workflow_dispatch:

jobs:
  post-tweet:
    runs-on: ubuntu-latest

    env:
      GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run Twitter Agent
        run: node index.js
